### ISSUE TITLE
"Evaluation tags" link is broken on the "Syntax Overview" page

### ISSUE THREAD

**Issue by Arturace** [squirrellyjs/squirrelly-docs#15]
See the [syntax overview](https://squirrelly.js.org/docs/syntax/overview/) page, the `Evaluation tags` link goes to `https://squirrelly.js.org/docs/syntax/overview/native-code` instead of `https://squirrelly.js.org/docs/syntax/native-code/`

**Comment by bgub** [comment]
Thanks for the heads up! I'll fix that right now.

Sorry for the late replies (I've been busy with graduating school and starting a new job).

**Comment by Arturace** [comment]
All good and understandable. Nothing that a little tinkering could not solve.
