### ISSUE TITLE
Performance page

### ISSUE THREAD

**Issue by Indribell** [squirrellyjs/squirrelly-docs#17]
On the page:

https://squirrelly.js.org/docs/about/performance/

1. The link:

https://cdn.statically.io/gh/squirrellyjs/squirrelly/master/browser-tests/benchmark.html

1. The Issue:

The following result is show:

> 400 Bad Request. The user is not registered with the HTML service. To enable the service please contact https://twitter.com/staticallyio

2. The link:

https://github.com/nebrelbug/squirrelly-benchmarks

2. The Issue:

The data that links to squirrelly's benchmarks is out of date. These are 2+ year old ( version squirrelly": "^6.1.0 according to the source and last git commit / run ). Maybe its better to add a warning?

**Comment by bgub** [comment]
@Indribell thanks for letting me know! I'll try to fix the link sometime later this week.

> The data that links to squirrelly's benchmarks is out of date

I just updated them :+1:

**Comment by bgub** [comment]
Just fixed the links in the docs as well, so I'll close this. Thanks for reporting it!
